# Generated by Django 3.2.6 on 2021-08-30 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='topic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='messages', to='chat.topic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='reply',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chat.message'),
        ),
    ]
